[alembic]
script_location = backend/migrations
prepend_sys_path = .
path_separator = os
sqlalchemy.url = mysql+pymysql://unused:unused@127.0.0.1/unused

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys =

[formatters]
keys = generic

[logger_root]
level = WARN
handlers =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
